# 
# Jekyll config file.
# Used for settings that affect the whole site.
# Also values which Jekyll expects you to set up once and rarely edit.

# If you are editing this file often after setup:
# Investigate # Jekyll's `data files` feature for the data you need to
# update frequently.

# File is *NOT* reloaded automatically
# Restart the server process. after changes to this file.
# Use 'bundle exec jekyll serve'.

# Access site settings via e.g. {{ site.title }}, {{ site.email }}.
# Any custom variable you create will be accessible in the templates
# via {{ site.myvariable }}.

# Working with YAML variables
# https://idratherbewriting.com/documentation-theme-jekyll/mydoc_yaml_tutorial#example-6-variables

# BTW: >- means to ignore newlines until next colon entry e.g. "baseurl:".

#######################
# Theme Settings
# Documented in minimal-mistakes _config.yml
# Theme w/nice infra at version for github pages
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : air # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

#######################
# Site Settings
locale                   : "en-US"
title                    : "4400"
title_separator          : "-"
subtitle                 : "Home Page"
name                     : "Jason Hemann"
description              : "Hemann's Programming Languages Course"
github                   : [metadata]
# e.g. http://example.com
url                      : "http://jasonhemann.github.io" 
# the site subpath, e.g. /blog
baseurl                  : "/21FA-CS4400"
repository               : "http://github.com/jasonhemann/21FA-CS4400
teaser                   : "/assets/images/500x300teaser.png" 
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : "21FA 4400"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

search                   : true 
search_full_content      : true
search_provider          : lunr # algolia
# algolia:
#   application_id         : # YOUR_APPLICATION_ID
#   index_name             : # YOUR_INDEX_NAME
#   search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
#   powered_by             : # true (default), false

# Social Sharing
# twitter:
#   username               : 
# facebook:
#   username               :
#   app_id                 :
#   publisher              :
# og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  links: # An array of links to social media profiles
  - "https://twitter.com/jhemann"
  - "https://stackexchange.com/users/5478012/"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# Site Author
author:
  name             : Jason Hemann
  avatar           : "https://avatars3.githubusercontent.com/u/1329370" 
  bio              : "The instructor: I like PL, LP, CLP; <br /> not so much CPL."
  location         : "Northeastern University"
  email            : "jhemann@northeastern.edu"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://hemann.pl"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jhemann"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jasonhemann"
    - label: "StackOverflow"
      icon: "fas fa-fw fa-link"
      url: "https://stackoverflow.com/users/4355474"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/jhemann/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jhemann"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jasonhemann"
    - label: "StackOverflow"
      icon: "fas fa-fw fa-link"
      url: "https://stackoverflow.com/users/4355474"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/jhemann/"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - "**/.#*"  # ignore open files
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
          
collections:
  enrichment:
    output: true
    permalink: /:collection/:path/
  FAQ:
    output: true
    permalink: /:collection/:path/
  lec:
    output: true
    permalink: /:collection/:path/
  people:
    output: true
    permalink: /:collection/:path/
  labs:
    output: true
    permalink: /:collection/:path/
  hw:
    output: true
    permalink: /:collection/:path/
    
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
    values:
      author_profile: false
      toc: false
      toc_icon: "cog"
      sidebar:
        title: "Site Map"
        nav: sidebar-site-map
      read_time: false
      comments: false
      share: false
      related: false
  # _hw
  - scope:
      path: ""
      type: hw
    values:
      layout: single
  # _FAQ
  - scope:
      path: ""
      type: FAQ
    values:
      layout: single
  # _lec
  - scope:
      path: ""
      type: lec
    values:
      layout: single
